grade = 0

print("ISA - Quiz 5")

print("\n1. What is machine code?")
print(" ")
print("\ta. A low-level programming language consisting of hexadecimal digits that make up high-level language instructions")
print("\tb. A low-level programming language consisting of binary digits/bits that the computer reads and understands")
print("\tc. A high-level programming language consisting of instruction lists that humans can read and understand")
print("\td. A medium-level programming language consisting of the assembly code designed for the computer processor")
print(" ")
choice = input("Enter choice: ")
if choice == "b":
  print("\nCorrect!")
  grade = grade + 20
else:
  print("\nIncorrect!")

print("\n2. What is the best definition of a script?")
print(" ")
print("\ta. It's an error message generated by the interpreter")
print("\tb. It's a text file that contains instructions which make up a Python program")
print("\tc. It's an error message generated by the compiler")
print("\td. It's a text file that contains sequences of zeroes and ones")
print(" ")
choice = input("Enter choice: ")
if choice == "b":
  print("\nCorrect!")
  grade = grade + 20
else:
  print("\nIncorrect!")

print("\n3. What is the expected behavior of the following program?")
print(" ")
print("prin(\"Goodbye!\")")
print(" ")
print("\ta. The program will output (\"Goodbye!\")")
print("\tb. The program will output Goodbye! to the screen")
print("\tc. The program will generate an error message on the screen")
print("\td. The program will output \"Goodbye!\"")
print(" ")
choice = input("Enter choice: ")
if choice == "c":
  print("\nCorrect!")
  grade = grade + 20
else:
  print("\nIncorrect!")

print("\n4. What is the expected behavior of the following program?")
print(" ")
print("print(\"Hello!\")")
print(" ")
print("\ta. The program will generate an error message on the screen")
print("\tb. The program will output Hello! to the screen")
print("\tc. The program will output \"Hello!\" to the screen")
print("\td. The program will output (\"Hello!\") to the screen")
print(" ")
choice = input("Enter choice: ")
if choice == "b":
  print("\nCorrect!")
  grade = grade + 20
else:
  print("\nIncorrect!")

print("\n5. What do you call a file containing a program written in a high-level programming language?")
print(" ")
print("\ta. A code file")
print("\tb. A target file")
print("\tc. A source file")
print("\td. A machine file")
print(" ")
choice = input("Enter choice: ")
if choice == "c":
  print("\nCorrect!")
  grade = grade + 20
else:
  print("\nIncorrect!")

print("\nGrade = " + str(grade))